"""
merge_elk_plugin.py
Merges elk.bundled.js and flow_x_plugin_local_elk.js into a single plugin file.
Handles Electron UMD module detection to ensure ELK loads into global scope.

Usage:
    python merge_elk_plugin.py

Repository: https://github.com/imasmo/flowchart-layout-tool
License: MIT
"""
import os
import sys

# Obtain the directory where the script is located
script_dir = os.path.dirname(os.path.abspath(__file__))

elk_file = os.path.join(script_dir, "elk.bundled.js")
plugin_file = os.path.join(script_dir, "flow_x_plugin_with_elk.js")
output_file = os.path.join(script_dir, "flow_x_plugin.js")


for f in [elk_file, plugin_file]:
    if not os.path.exists(f):
        print("Error: file not found - " + f)
        sys.exit(1)

with open(elk_file, "r", encoding="utf-8") as f:
    elk_code = f.read()

with open(plugin_file, "r", encoding="utf-8") as f:
    plugin_code = f.read()

lines = []

# ---- Header ----
lines.append('// ================================================================')
lines.append('// Flow X Plugin with ELK - Merged Single File')
lines.append('// Generated by merge_elk_plugin.py')
lines.append('// ================================================================')
lines.append('')
lines.append('console.log("[FlowX-merge] ====== Loading started ======");')
lines.append('console.log("[FlowX-merge] typeof module =", typeof module);')
lines.append('console.log("[FlowX-merge] typeof exports =", typeof exports);')
lines.append('console.log("[FlowX-merge] typeof define =", typeof define);')
lines.append('console.log("[FlowX-merge] typeof require =", typeof require);')
lines.append('console.log("[FlowX-merge] typeof window =", typeof window);')
lines.append('')

# ---- Save original module.exports ----
lines.append('var __fx_orig_me = null;')
lines.append('try {')
lines.append('    if (typeof module !== "undefined" && module && module.exports) {')
lines.append('        __fx_orig_me = module.exports;')
lines.append('    }')
lines.append('} catch(e) {}')
lines.append('')

# ---- Execute elk.bundled.js ----
lines.append('console.log("[FlowX-merge] Executing elk.bundled.js ...");')
lines.append('try {')
lines.append('')
lines.append('// ---- elk.bundled.js START ----')
lines.append(elk_code)
lines.append('// ---- elk.bundled.js END ----')
lines.append('')
lines.append('    console.log("[FlowX-merge] elk.bundled.js executed successfully");')
lines.append('} catch(__elk_err) {')
lines.append('    console.error("[FlowX-merge] elk.bundled.js execution error:", __elk_err);')
lines.append('    console.error("[FlowX-merge] Stack:", __elk_err.stack);')
lines.append('}')
lines.append('')

# ---- Detect where ELK landed ----
lines.append('console.log("[FlowX-merge] --- Detecting ELK location ---");')
lines.append('var __fx_elk = null;')
lines.append('')

# Location 1: Global ELK
lines.append('try {')
lines.append('    if (typeof ELK !== "undefined") {')
lines.append('        __fx_elk = ELK;')
lines.append('        console.log("[FlowX-merge] Found: global ELK, type=" + typeof ELK);')
lines.append('    } else {')
lines.append('        console.log("[FlowX-merge] Global ELK: undefined");')
lines.append('    }')
lines.append('} catch(e) { console.log("[FlowX-merge] Check global ELK error:", e.message); }')
lines.append('')

# Location 2: window.ELK
lines.append('if (!__fx_elk) {')
lines.append('    try {')
lines.append('        if (typeof window !== "undefined" && typeof window.ELK !== "undefined") {')
lines.append('            __fx_elk = window.ELK;')
lines.append('            console.log("[FlowX-merge] Found: window.ELK, type=" + typeof window.ELK);')
lines.append('        } else {')
lines.append('            console.log("[FlowX-merge] window.ELK: undefined");')
lines.append('        }')
lines.append('    } catch(e) { console.log("[FlowX-merge] Check window.ELK error:", e.message); }')
lines.append('}')
lines.append('')

# Location 3: module.exports
lines.append('if (!__fx_elk) {')
lines.append('    try {')
lines.append('        if (typeof module !== "undefined" && module && module.exports) {')
lines.append('            console.log("[FlowX-merge] module.exports type=" + typeof module.exports);')
lines.append('            if (module.exports !== __fx_orig_me) {')
lines.append('                console.log("[FlowX-merge] module.exports was modified by elk!");')
lines.append('                if (typeof module.exports === "function") {')
lines.append('                    __fx_elk = module.exports;')
lines.append('                    console.log("[FlowX-merge] Found: module.exports (function)");')
lines.append('                } else if (module.exports && module.exports.default) {')
lines.append('                    __fx_elk = module.exports.default;')
lines.append('                    console.log("[FlowX-merge] Found: module.exports.default");')
lines.append('                } else if (typeof module.exports === "object") {')
lines.append('                    var _keys = Object.keys(module.exports);')
lines.append('                    console.log("[FlowX-merge] module.exports keys: " + _keys.join(", "));')
lines.append('                    for (var _k = 0; _k < _keys.length; _k++) {')
lines.append('                        if (typeof module.exports[_keys[_k]] === "function") {')
lines.append('                            __fx_elk = module.exports[_keys[_k]];')
lines.append('                            console.log("[FlowX-merge] Found: module.exports." + _keys[_k]);')
lines.append('                            break;')
lines.append('                        }')
lines.append('                    }')
lines.append('                }')
lines.append('            } else {')
lines.append('                console.log("[FlowX-merge] module.exports not modified");')
lines.append('            }')
lines.append('        } else {')
lines.append('            console.log("[FlowX-merge] module not available or no exports");')
lines.append('        }')
lines.append('    } catch(e) { console.log("[FlowX-merge] Check module.exports error:", e.message); }')
lines.append('}')
lines.append('')

# Location 4: require
lines.append('if (!__fx_elk) {')
lines.append('    try {')
lines.append('        if (typeof require === "function") {')
lines.append('            var _reqElk = require("elkjs");')
lines.append('            if (_reqElk) {')
lines.append('                __fx_elk = _reqElk.default || _reqElk;')
lines.append('                console.log("[FlowX-merge] Found: require elkjs");')
lines.append('            }')
lines.append('        }')
lines.append('    } catch(e) { console.log("[FlowX-merge] require failed:", e.message); }')
lines.append('}')
lines.append('')

# Save to window and verify
lines.append('if (__fx_elk) {')
lines.append('    window.__FlowX_ELK = __fx_elk;')
lines.append('    console.log("[FlowX-merge] ELK saved to window.__FlowX_ELK");')
lines.append('    try {')
lines.append('        var _testElk = new __fx_elk();')
lines.append('        console.log("[FlowX-merge] new ELK() succeeded");')
lines.append('        if (typeof _testElk.layout === "function") {')
lines.append('            console.log("[FlowX-merge] elk.layout() method available");')
lines.append('        } else {')
lines.append('            console.log("[FlowX-merge] Warning: elk.layout() method not found");')
lines.append('        }')
lines.append('    } catch(e) {')
lines.append('        console.error("[FlowX-merge] new ELK() failed:", e.message);')
lines.append('    }')
lines.append('} else {')
lines.append('    console.error("[FlowX-merge] ELK not found in any location!");')
lines.append('    console.error("[FlowX-merge] Please screenshot the above logs and report to developer");')
lines.append('}')
lines.append('')
lines.append('console.log("[FlowX-merge] ====== ELK loading phase complete ======");')
lines.append('')

# ---- Plugin code ----
lines.append('// ================================================================')
lines.append('// PART 2: Flow X Plugin')
lines.append('// ================================================================')
lines.append(plugin_code)

# Write output
with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

size_kb = os.path.getsize(output_file) / 1024
print("OK: " + output_file)
print("Size: {:.1f} KB".format(size_kb))
print("")
print("Next steps:")
print("  1. draw.io -> Extras -> Plugins")
print("  2. Delete old plugins")
print("  3. Add -> select flow_x_final.js")
print("  4. Restart draw.io")
print("  5. Ctrl+Shift+I -> check Console logs")